/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Driver;
import Admin.CustomerManage;
import Bank.Verification;
import Model.*;
import InterfaceDB.koneksi;
import Pelanggan.BayarTagihan;
import Pelanggan.Register;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Login extends javax.swing.JFrame {
PreparedStatement pre=null;
Connection conn=koneksi.getConnection();;
ResultSet rs=null;
modelPelanggan MP = new modelPelanggan();
modelAdmin MA = new modelAdmin();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
       SeparatorLine.setVisible(false);
       BTN_SignUp.setVisible(false);  
       txt_username.setEditable(false);
       txt_password.setEditable(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RoleGroupLogin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        RoleCustomers = new javax.swing.JRadioButton();
        RoleAdmin = new javax.swing.JRadioButton();
        RoleBank = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        BTN_SignUp = new javax.swing.JButton();
        BTN_SignIn = new javax.swing.JButton();
        SeparatorLine = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Password");

        RoleGroupLogin.add(RoleCustomers);
        RoleCustomers.setText("CUSTOMERS");
        RoleCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleCustomersActionPerformed(evt);
            }
        });

        RoleGroupLogin.add(RoleAdmin);
        RoleAdmin.setText("ADMIN");
        RoleAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleAdminActionPerformed(evt);
            }
        });

        RoleGroupLogin.add(RoleBank);
        RoleBank.setText("BANK");
        RoleBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleBankActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(RoleCustomers)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoleAdmin)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RoleBank)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RoleCustomers)
                            .addComponent(RoleBank)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RoleAdmin))))
                .addContainerGap())
        );

        BTN_SignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Create Sign UP.png"))); // NOI18N
        BTN_SignUp.setText("Sign up");
        BTN_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SignUpActionPerformed(evt);
            }
        });

        BTN_SignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Sign in.png"))); // NOI18N
        BTN_SignIn.setText("Sign in");
        BTN_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SignInActionPerformed(evt);
            }
        });

        SeparatorLine.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Algerian", 2, 24)); // NOI18N
        jLabel3.setText("E  Pay");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logi Listrik.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Created.png"))); // NOI18N
        jLabel6.setText("MADE By GROUP 3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTN_SignUp)
                        .addGap(26, 26, 26)
                        .addComponent(SeparatorLine, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTN_SignIn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)
                        .addComponent(txt_username)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_SignUp)
                            .addComponent(BTN_SignIn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SeparatorLine, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RoleCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleCustomersActionPerformed
       SeparatorLine.setVisible(true);
       BTN_SignUp.setVisible(true);
       txt_username.setEditable(true);
       txt_password.setEditable(true);
    }//GEN-LAST:event_RoleCustomersActionPerformed

    private void RoleAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleAdminActionPerformed
       SeparatorLine.setVisible(false);
       BTN_SignUp.setVisible(false);
       txt_username.setEditable(true);
       txt_password.setEditable(true);
    }//GEN-LAST:event_RoleAdminActionPerformed

    private void RoleBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleBankActionPerformed
       SeparatorLine.setVisible(false);
       BTN_SignUp.setVisible(false);
       txt_username.setEditable(true);
       txt_password.setEditable(true);
    }//GEN-LAST:event_RoleBankActionPerformed

    private void BTN_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SignInActionPerformed
       String username = txt_username.getText();
       String password = txt_password.getText();
       
       
       try{
         if(RoleCustomers.isSelected())
         {
         pre = conn.prepareStatement("select * from pelanggan where username=? and password=?");
         pre.setString(1, username);
         pre.setString(2, password);
         rs = pre.executeQuery();
         if(rs.next())
         {
             MP.setId_pelanggan(rs.getString("id_pelanggan"));
             MP.setUsername(rs.getString("Username"));
             MP.setPassword(rs.getString("Password"));
             MP.setNama_pelanggan(rs.getString("nama_pelanggan"));
             MP.setAlamat(rs.getString("alamat"));
             MP.setNomer_KWH(rs.getString("nomor_KWH"));
             MP.setId_tarif(rs.getString("id_tarif"));
         }
         
            if(username.equals(MP.getUsername())&& password.equals(MP.getPassword())){
                   JOptionPane.showMessageDialog(null, "Login Succes!");
                   new BayarTagihan().main(MP.getId_pelanggan(),null);
                   this.setVisible(false);
            }
            else{
                   JOptionPane.showMessageDialog(null, "Username OR Password Wrong!");
                }
        }
         else if(RoleBank.isSelected())
         {
            if(String.valueOf(txt_username.getText()).equals("bank") && String.valueOf(txt_password.getText()).equals("12345"))
            {
                JOptionPane.showMessageDialog(null, "Login Succes!");
                new Verification().setVisible(true);
                   this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Username OR Password Wrong!");
            }
         }
         else if(RoleAdmin.isSelected())
         {
            pre = conn.prepareStatement("select * from admin where username=? and password=?");
         pre.setString(1, username);
         pre.setString(2, password);
         rs = pre.executeQuery();
         if(rs.next())
         {
             MA.setId_admin(rs.getString("id_admin"));
             MA.setUsername(rs.getString("Username"));
             MA.setPassword(rs.getString("Password"));
             MA.setNama_admin(rs.getString("nama_admin"));
             MA.setId_level(rs.getString("id_level"));
         }
         
            if(username.equals(MA.getUsername())&& password.equals(MA.getPassword())){
                   JOptionPane.showMessageDialog(null, "Login Succes!");
                   new CustomerManage().main(MA.getId_admin(),null);
                   this.setVisible(false);
            }
            else{
                   JOptionPane.showMessageDialog(null, "Username OR Password Wrong!");
                } 
         }
         }
        catch(SQLException ex)
        {
        }
    
    }//GEN-LAST:event_BTN_SignInActionPerformed

    private void BTN_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SignUpActionPerformed
       new Register().setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_BTN_SignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_SignIn;
    private javax.swing.JButton BTN_SignUp;
    private javax.swing.JRadioButton RoleAdmin;
    private javax.swing.JRadioButton RoleBank;
    private javax.swing.JRadioButton RoleCustomers;
    private javax.swing.ButtonGroup RoleGroupLogin;
    private javax.swing.JSeparator SeparatorLine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
